repos:
  - repo: https://github.com/nozaq/pre-commit-deno
    rev: '0.1.0'
    hooks:
     - id: deno-fmt-check
       args: ["--config", "./deno.jsonc", "--unstable"]
     - id: deno-lint
       args: ["--config", "./deno.jsonc", "--unstable"]
