[last_fm]
username=""
api_key=""

[twitter]
api_key=""
api_key_secret=""
access_token=""
access_token_secret=""

[discord]
application_id=""
public_key=""

[app.nowplaying]
enabled=true

[app.nowplaying.twitter]
enabled=true
upload_image=true
template=""

[app.nowplaying.discord]
enabled=true

[app.nowplaying.discord.template]
state="Playing {track}..."
detail="{artist} - {album}"
