[last_fm]
username=""
api_key=""

[twitter]
api_key=""
api_key_secret=""
access_token=""
access_token_secret=""

[discord]
application_id=""
public_key=""

[config]
# daily_update=true
# daily_update_hour=00
# daily_update_minute=00
nowplaying_update=true
nowplaying_update_to_twitter=false
nowplaying_update_to_discord=true
